# Generated by Django 4.2.11 on 2024-03-25 20:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='dailydata',
            options={'ordering': ['-date_data']},
        ),
    ]
